! Startup-config last modified at Thu Aug 20 19:18:50 2026 by root
! device: rda11 (cEOSLab, EOS-4.36.1F-48405728.4361F (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$yRV11/DACVliZ0rc$3AR8zdYWHj6kP/ORBlhsh3d8nkBCDq5uP.PU20F6jFYmgd3E8mUZBPmvM7MD1u7p9oTfXO8XJEpD6jrTUdvNl1
!
management api http-commands
   no shutdown
!
no service interface inactive port-id allocation disabled
!
service routing protocols model multi-agent
!
hostname rda11
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
management api gnmi
   transport grpc default
!
management api netconf
   transport ssh default
!
interface Ethernet1
   no switchport
   ip address 10.101.2.11/24
!
interface Ethernet2
   no switchport
   ip address 10.101.3.11/24
!
interface Ethernet3
   no switchport
   ip address 10.1.123.1/24
!
interface Loopback0
   ip address 100.1.1.1/32
!
interface Management0
   ip address 1.1.1.1/8
!
ip routing
!
router ospf 1
   router-id 100.1.1.1
   network 10.1.123.0/24 area 0.0.0.1
   network 10.101.2.0/24 area 0.0.0.1
   network 10.101.3.0/24 area 0.0.0.1
   network 100.1.1.1/32 area 0.0.0.1
   max-lsa 12000
!
end
