!
! FRR Configuration with full northbound API support
!
frr version 8.4
frr defaults datacenter
hostname frr-router
service integrated-vtysh-config
log file /var/log/frr/ospfd.log debugging
!
interface Loopback0
ip address 7.7.7.7 255.255.255.255
!
interface Loopback1
ip address 192.168.5.7 255.255.255.0
!
interface Loopback10
no ip address
!
interface eth0
ip address 192.168.6.7 255.255.255.0
!
interface eth1
ip address 20.20.30.7 255.255.255.0
!
router ospf
router-id 7.7.7.7
network 192.168.6.0/24 area 2
network 192.168.5.0/24 area 2
network 7.7.7.7/32 area 2
network 20.20.30.0/24 area 0
area 2 virtual-link 3.3.3.3
! Enable SNMP AgentX
agentx
!
end