! Startup-config last modified at Thu Aug 20 19:19:25 2026 by root
! device: rdb12 (cEOSLab, EOS-4.36.1F-48405728.4361F (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$Osqrj7UOgbvZkfen$0HcBYrv6sYM9LsEkMSDwu1/GHhCrMdlBHIstP.v5xXnAHLUyiOOk84gNhEPntjriIFTDcGhwLeo8YQhFNzDpI1
!
management api http-commands
   no shutdown
!
no service interface inactive port-id allocation disabled
!
service routing protocols model multi-agent
!
hostname rdb12
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
management api gnmi
   transport grpc default
!
management api netconf
   transport ssh default
!
interface Ethernet1
   no switchport
   ip address 20.101.12.12/24
   isis enable 1
!
interface Loopback0
   ip address 100.2.1.2/32
   isis enable 1
!
interface Management0
   ip address 1.2.1.2/8
!
ip routing
!
router isis 1
   net 49.0000.0000.0000.0002.1111.0000.0002.0002.00
   is-type level-1
   !
   address-family ipv4 unicast
!
end
