! Startup-config last modified at Thu Aug 20 19:18:45 2026 by root
! device: rda31 (cEOSLab, EOS-4.36.1F-48405728.4361F (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$iYI1HYSMyugGK451$bGK/xu1sydVCHmYp2K2w/5WpHKcggIKW563vGfOKRN5TuuRTgPompH6LCz1rWimp0pFfnBoir0IrtgJ6lA/bL/
!
management api http-commands
   no shutdown
!
no service interface inactive port-id allocation disabled
!
service routing protocols model multi-agent
!
hostname rda31
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
management api gnmi
   transport grpc default
!
management api netconf
   transport ssh default
!
interface Ethernet1
   no switchport
   ip address 10.103.5.31/24
!
interface Ethernet2
   no switchport
   ip address 10.3.12.1/24
!
interface Loopback0
   ip address 100.1.3.1/32
!
interface Management0
   ip address 1.1.3.1/8
!
ip routing
!
router ospf 1
   router-id 100.1.3.1
   area 0.0.0.3 stub
   network 10.3.12.0/24 area 0.0.0.3
   network 10.103.5.0/24 area 0.0.0.3
   network 100.1.3.1/32 area 0.0.0.3
   max-lsa 12000
!
end
