! Startup-config last modified at Thu Aug 20 19:18:43 2026 by root
! device: rcb2 (cEOSLab, EOS-4.36.1F-48405728.4361F (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$FlnTOS3d5b072sPE$mTbLcrpleo40dpoAlRKBEy7/NxiCE0VXmk505FQ7VzRwUli/U4qLB8rAcbmmTpYg7MAOQc/8pG6yDkZGk4fWj.
!
management api http-commands
   no shutdown
!
no service interface inactive port-id allocation disabled
!
service routing protocols model multi-agent
!
hostname rcb2
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
management api gnmi
   transport grpc default
!
management api netconf
   transport ssh default
!
interface Ethernet1
   no switchport
   ip address 120.0.2.1/31
!
interface Ethernet2
   no switchport
   ip address 20.0.12.2/24
   isis enable 1
!
interface Ethernet3
   no switchport
   ip address 20.0.23.2/24
   isis enable 1
!
interface Loopback0
   ip address 100.2.0.2/32
   isis enable 1
!
interface Management0
   ip address 1.2.0.2/8
!
ip routing
!
ip prefix-list AS1-AGGR seq 10 permit 10.0.0.0/8
ip prefix-list AS1-AGGR seq 20 permit 100.1.0.0/16
ip prefix-list AS2-AGGR seq 10 permit 20.0.0.0/8
ip prefix-list AS2-AGGR seq 20 permit 100.2.0.0/16
!
ip route 20.0.0.0/8 Null0
ip route 100.2.0.0/16 Null0
!
route-map AS1-IN permit 10
   match ip address prefix-list AS1-AGGR
!
route-map AS1-OUT permit 10
   match ip address prefix-list AS2-AGGR
!
router bgp 2
   router-id 100.2.0.2
   no bgp default ipv4-unicast
   neighbor 100.2.0.1 remote-as 2
   neighbor 100.2.0.1 update-source Loopback0
   neighbor 100.2.0.1 description iBGP-to-RCB1
   neighbor 120.0.2.0 remote-as 1
   neighbor 120.0.2.0 description eBGP-to-RCA2
   !
   address-family ipv4
      neighbor 100.2.0.1 activate
      neighbor 100.2.0.1 next-hop-self
      neighbor 120.0.2.0 activate
      neighbor 120.0.2.0 route-map AS1-IN in
      neighbor 120.0.2.0 route-map AS1-OUT out
      network 20.0.0.0/8
      network 100.2.0.0/16
!
router isis 1
   net 49.0000.0000.0000.0001.1111.0000.0000.0002.00
   is-type level-2
   log-adjacency-changes
   !
   address-family ipv4 unicast
      redistribute bgp route-map AS1-IN
!
end
