! Startup-config last modified at Thu Aug 20 19:18:49 2026 by root
! device: rca1 (cEOSLab, EOS-4.36.1F-48405728.4361F (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$M3H99ouAy/yStDqu$DrpbfxJSVOdsJsCQCjsgl4lJwCqb/2oBxXLMFz8rzQ11jWPCUUBZ1ZTsxPbt7vFXlvHt4IoLLZGVaJMMIfz1..
!
management api http-commands
   no shutdown
!
no service interface inactive port-id allocation disabled
!
service routing protocols model multi-agent
!
hostname rca1
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
management api gnmi
   transport grpc default
!
management api netconf
   transport ssh default
!
interface Ethernet1
   no switchport
   ip address 10.0.12.1/24
!
interface Ethernet2
   no switchport
   ip address 10.0.14.1/24
!
interface Ethernet3
   no switchport
   ip address 10.0.13.1/24
!
interface Ethernet5
   no switchport
   ip address 120.0.1.0/31
!
interface Loopback0
   ip address 100.1.0.1/32
!
interface Management0
   ip address 1.1.0.1/8
!
ip routing
!
ip prefix-list AS1-AGGR seq 10 permit 10.0.0.0/8
ip prefix-list AS1-AGGR seq 20 permit 100.1.0.0/16
ip prefix-list AS2-AGGR seq 10 permit 20.0.0.0/8
ip prefix-list AS2-AGGR seq 20 permit 100.2.0.0/16
!
ip route 10.0.0.0/8 Null0
ip route 100.1.0.0/16 Null0
!
route-map AS2-IN permit 10
   match ip address prefix-list AS2-AGGR
!
route-map AS2-OUT permit 10
   match ip address prefix-list AS1-AGGR
!
router bgp 1
   router-id 100.1.0.1
   neighbor 100.1.0.2 remote-as 1
   neighbor 100.1.0.2 update-source Loopback0
   neighbor 100.1.0.2 description iBGP-to-RCA2
   neighbor 120.0.1.1 remote-as 2
   neighbor 120.0.1.1 description eBGP-to-RCB1
   !
   address-family ipv4
      neighbor 100.1.0.2 activate
      neighbor 100.1.0.2 next-hop-self
      neighbor 120.0.1.1 activate
      neighbor 120.0.1.1 route-map AS2-IN in
      neighbor 120.0.1.1 route-map AS2-OUT out
      network 10.0.0.0/8
      network 100.1.0.0/16
!
router ospf 1
   router-id 100.1.0.1
   redistribute bgp route-map AS2-IN
   network 10.0.12.0/24 area 0.0.0.0
   network 10.0.13.0/24 area 0.0.0.0
   network 10.0.14.0/24 area 0.0.0.0
   network 100.1.0.1/32 area 0.0.0.0
   max-lsa 12000
!
end
