! Startup-config last modified at Thu Aug 20 19:18:38 2026 by root
! device: rca2 (cEOSLab, EOS-4.36.1F-48405728.4361F (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$c.R9hVQrD60wkUF7$PdmcgssrU4WIxR9GeGGX7RlmtJ.ipHYTh2GxVg3kydPKFQehyLE7SxjVrDCIenCKZdVCgK05s3CWSHeRIHZdB0
!
management api http-commands
   no shutdown
!
no service interface inactive port-id allocation disabled
!
service routing protocols model multi-agent
!
hostname rca2
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
management api gnmi
   transport grpc default
!
management api netconf
   transport ssh default
!
interface Ethernet1
   no switchport
   ip address 10.0.12.2/24
!
interface Ethernet2
   no switchport
   ip address 10.0.23.2/24
!
interface Ethernet3
   no switchport
   ip address 10.0.24.2/24
!
interface Ethernet4
   no switchport
   ip address 10.101.2.2/24
!
interface Ethernet5
   no switchport
   ip address 120.0.2.0/31
!
interface Loopback0
   ip address 100.1.0.2/32
!
interface Management0
   ip address 1.1.0.2/8
!
ip routing
!
ip prefix-list AS1-AGGR seq 10 permit 10.0.0.0/8
ip prefix-list AS1-AGGR seq 20 permit 100.1.0.0/16
ip prefix-list AS2-AGGR seq 10 permit 20.0.0.0/8
ip prefix-list AS2-AGGR seq 20 permit 100.2.0.0/16
!
route-map AS2-IN permit 10
   match ip address prefix-list AS2-AGGR
!
route-map AS2-OUT permit 10
   match ip address prefix-list AS1-AGGR
!
router bgp 1
   router-id 100.1.0.2
   no bgp default ipv4-unicast
   neighbor 100.1.0.1 remote-as 1
   neighbor 100.1.0.1 update-source Loopback0
   neighbor 100.1.0.1 description iBGP-to-RCA1
   neighbor 120.0.2.1 remote-as 2
   neighbor 120.0.2.1 description eBGP-to-RCB2
   !
   address-family ipv4
      neighbor 100.1.0.1 activate
      neighbor 100.1.0.1 next-hop-self
      neighbor 120.0.2.1 activate
      neighbor 120.0.2.1 route-map AS2-IN in
      neighbor 120.0.2.1 route-map AS2-OUT out
      network 10.0.0.0/8
      network 100.1.0.0/16
!
router ospf 1
   router-id 100.1.0.2
   network 10.0.12.0/24 area 0.0.0.0
   network 10.0.23.0/24 area 0.0.0.0
   network 10.0.24.0/24 area 0.0.0.0
   network 10.101.2.0/24 area 0.0.0.1
   network 100.1.0.2/32 area 0.0.0.0
   max-lsa 12000
!
end
