! Startup-config last modified at Thu Aug 20 19:18:33 2026 by root
! device: rca3 (cEOSLab, EOS-4.36.1F-48405728.4361F (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$9NvOiyHFvB/HoJXL$TMEjeUJzlDZnR8KeqPhqaHug218LzXSZomw8jBe3O/Y19tS9Ol8b0UCxuGaUPv2s8IOGmHRXQcpRVETsu.hff1
!
management api http-commands
   no shutdown
!
no service interface inactive port-id allocation disabled
!
service routing protocols model multi-agent
!
hostname rca3
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
management api gnmi
   transport grpc default
!
management api netconf
   transport ssh default
!
interface Ethernet1
   no switchport
   ip address 10.0.23.3/24
!
interface Ethernet2
   no switchport
   ip address 10.0.34.3/24
!
interface Ethernet3
   no switchport
   ip address 10.0.13.3/24
!
interface Ethernet4
   no switchport
   ip address 10.101.3.3/24
!
interface Loopback0
   ip address 100.1.0.3/32
!
interface Management0
   ip address 1.1.0.3/8
!
interface Ethernet5
    no switchport
    ip address 10.0.35.3/24
!
ip routing
!
router ospf 1
   network 10.0.13.0/24 area 0.0.0.0
   network 10.0.23.0/24 area 0.0.0.0
   network 10.0.34.0/24 area 0.0.0.0
   network 10.0.35.0/24 area 0.0.0.0
   network 10.101.3.0/24 area 0.0.0.1
   network 100.1.0.3/32 area 0.0.0.0
   max-lsa 12000
   tunnel routes
!
end
