! Startup-config last modified at Thu Aug 20 19:18:47 2026 by root
! device: rca4 (cEOSLab, EOS-4.36.1F-48405728.4361F (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$TIY1UGyOCGQWQuy0$F5KTy6nJ.PFrQIwPHB11OQGiruNhV3HJzGcgqO1AOc6jL3koJJqVN6sJa/1ARgelQWEqxE/KKzRkZlfQc4EAp0
!
management api http-commands
   no shutdown
!
no service interface inactive port-id allocation disabled
!
service routing protocols model multi-agent
!
hostname rca4
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
management api gnmi
   transport grpc default
!
management api netconf
   transport ssh default
!
interface Ethernet1
   no switchport
   ip address 10.0.34.4/24
!
interface Ethernet2
   no switchport
   ip address 10.0.14.4/24
!
interface Ethernet3
   no switchport
   ip address 10.0.24.4/24
!
interface Ethernet5
   no switchport
   ip address 10.0.45.4/24
!
interface Loopback0
   ip address 100.1.0.4/32
!
interface Management0
   ip address 1.1.0.4/8
!
ip routing
!
router ospf 1
   router-id 100.1.0.4
   network 10.0.14.0/24 area 0.0.0.0
   network 10.0.24.0/24 area 0.0.0.0
   network 10.0.34.0/24 area 0.0.0.0
   network 10.0.45.0/24 area 0.0.0.0
   network 100.1.0.4/32 area 0.0.0.0
   max-lsa 12000
   tunnel routes
!
end
